server:
  port: ${serverPort:443}
  use-forward-headers: true
  ssl:
    key-store: ${keystoreLocation}
    key-store-password: ${keystorePassword}
    key-password: ${keystorePassword}
    key-alias: ${keystoreSSLKey:tomcat}
    enabled-protocols: TLSv1.2

aquarius:
  service:
    endpoint: ${aquariusServiceEndpoint}
    user: ${aquariusServiceUser}
    password: ${aquariusServicePassword}
    retries:
      unauthorized: ${aquariusUnauthorizedRetires:3}
  reference:
    modified: "2018-05-31T12:51:00-05:00"
    computations:
      - Decumulated
      - Max
      - Max At Event Time
      - Mean
      - Median
      - Min
      - SelectedValue
      - Sum
      - TidalHigh
      - TidalHigherLow
      - TidalLow
      - TidalLowerHigh
      - Variance
      - EquivalentMean
      - AM
      - Instantaneous
      - 120DayHighMean
      - 003DayHighMean
      - STD
      - Unknown
    periods:
      - Annual
      - Daily
      - Hourly
      - Monthly
      - Points
      - Water Year
      - Weekly
      - Unknown

security:
  require-ssl: true
  basic:
    enabled: false

management:
  security:
    enabled: false

eureka:
  client:
    enabled: false

spring:
  profiles:
    active: default, swagger
  application:
    name: aqcu-lookups
  jmx:
    default-domain: aqcu-lookups
